### ISSUE TITLE
"Projects must be configuring" error during Gradle configuration with Kodein 7.13.1 in Kotlin/JS project

### ISSUE THREAD

**Issue by NorbertSandor** [kosi-libs/Kodein#414]
I tried to add JS support (again) to my multi-platform multi-module project incrementally.
Besides other things, I found out that adding `org.kodein.di:kodein-di:7.13.1` as a JS project dependency produces the _"Projects must be configuring"_ error, while `org.kodein.di:kodein-di:7.13.0` does not.

Please see this issue for some more details: https://youtrack.jetbrains.com/issue/KT-52647

**Comment by romainbsl** [comment]
This issue is clearly not from us as we encounter it on no kodein dependent projects.
Closing the issue.
