### ISSUE TITLE
Kodein 7.13.1 released to Maven Central?

### ISSUE THREAD

**Issue by twyatt** [kosi-libs/Kodein#416]
My apologies if I'm just being impatient and the process just hasn't completed yet, but I saw that 7.13.1 was released ([according to GitHub releases](https://github.com/kosi-libs/Kodein/releases/tag/7.13.1)), but [Maven Central is showing 7.13.0 as the latest](https://search.maven.org/search?q=g:org.kodein.di):

![Screen Shot 2022-07-14 at 3 57 44 PM](https://user-images.githubusercontent.com/98017/179108750-654f372a-967a-4b96-9242-67f48c85c6c1.png)

**Comment by romainbsl** [comment]
How unfortunate! I don't even know how this is possible, as CI went all green. Let me rerun the release to see what happened. 
Thanks for the report

**Comment by romainbsl** [comment]
it is now live. 
https://repo1.maven.org/maven2/org/kodein/di/kodein-di/7.13.1/
I don't know why. Sorry for the inconvenience.
