### ISSUE TITLE
Composable 

### ISSUE THREAD

**Issue by dongzhaosheng73** [kosi-libs/Kodein#417]
```kotlin 
class MainActivity : ComponentActivity(), DIAware { 
  override val di by closestDI(AppEntry.instance)

  @Preview(showBackground = true)
  @Composable
  fun DefaultPreview() {
    withDI(di = androidContextDI()) {
        Greeting("Android")
    }
  }
}
```

Using previews when the app is not initialized will report that DI is not initialized. What should I do in this case?

```
error: java.lang.IllegalStateException: Trying to find closest DI, but no DI container was found at all. Your Application should be DIAware.
```

**Comment by romainbsl** [comment]
Obviously you cannot access the Application context has it is not initialized from the preview point of view.
In that case you could declare your DI as an internal variable like:

```kotlin
class KodeinSampleApp : Application(), DIAware {
    override val di: DI = internalDI
}

internal val internalDI: DI = DI {
    bindConstant("AUTHOR") { "Romain" }
}
```

Then you could use it in previews:


@Preview(showBackground = true)
@Composable
fun DefaultPreview() {
    KodeinSampleTheme {
        withDI(di = internalDI) {
            val author: String by rememberInstance("AUTHOR")
            Greeting(author.uppercase())
        }
    }
}

**Comment by GSculerlor** [comment]
sorry for necroposting/bumping this closed issue, but is there any way to make the preview work without declaring the DI as a variable? or is that the only way to make previewing Composable function with injected instance works?
