### ISSUE TITLE
Support Compose for iOS

### ISSUE THREAD

**Issue by VladislavSumin** [kosi-libs/Kodein#418]
In release notes for release 7.14.0 declared support for compose 1.2.0-alpha01-dev745, but targets for ios now unsupported:

`:client:ios:uikitArm64Main: Could not resolve org.kodein.di:kodein-di-framework-compose:7.14.0.`

**Comment by romainbsl** [comment]
Available since [7.15.1](https://github.com/kosi-libs/Kodein/releases/tag/7.15.1).
