### ISSUE TITLE
Kodein DI on Ktor documentation is wrong

### ISSUE THREAD

**Issue by bdudelsack** [kosi-libs/Kodein#422]
The `DIPlugin` (kodein-di-framework-ktor-server-jvm) for the Ktor Framework does not have `di()` extension as stated in the documentation at: 

https://kosi-libs.org/kodein-di/7.12.0/framework/ktor.html

When i see right only `closestDI` extension is available (https://github.com/kosi-libs/Kodein/blob/master/framework/ktor/kodein-di-framework-ktor-server-jvm/src/main/kotlin/org/kodein/di/ktor/closest.kt).

Call to `di()` should be replaced with `closestDI()` in all examples.

UPDATE: If the use of `di()` is intended, then the following import must be documented:
```kotlin
import org.kodein.di.ktor.closestDI as di
```

**Comment by romainbsl** [comment]
Documentation has been updated. Thank you for your contribution.
