### ISSUE TITLE
For versions >= 7.12.0 not resolving in KMM project

### ISSUE THREAD

**Issue by dalewking** [kosi-libs/Kodein#428]
This is perhaps more of a question than an issue

I am trying to upgrade Kodein for a Kotlin multiplatform application that has been happily using Kodein for 2-3 years. I can upgrade it up to 7.11.0 with no issue. But starting with 7.12.0 I get errors from gradle like:

> Could not resolve org.kodein.di:kodein-di:7.12.0

That is the only change, switching version numbers to Kodein and I get that error. I tried all the later versions and I get the same error.

I tried creating a new KMM project and adding a dependency on kodein and it had no problems.

Just wondering what could have changed between 7.11.0 and 7.12.0 that could cause this.

**Comment by romainbsl** [comment]
Hey @dalewking sorry to here that. 

The main differences I see are:
- Kotlin 16.10 to 1.6.21
- Gradle 7.2 to 7.4.2
- + Apple Silicon support
- Android publication fixes

What versions are you targeting ?
Is your project open source, so I could check?

**Comment by dalewking** [comment]
We are in the process of trying to get everything updated. It was on Kotlin 1.5.31 and when I was trying this it was with 1.6.21. I was trying to get everything updated to the latest version that was pre-1.7 before moving on to 1.7. We were also switching from the old style of declaring iOS projects (Workaround 1 here: https://kotlinlang.org/docs/multiplatform-hierarchy.html#for-multiplatform-project-authors) to hierarchical projects.

The good news is now that I am working on 1.7.21 upgrade I don't seem to have this problem anymore (although iOS is failing due to DI so still investigating that and am hoping upgrading Kodein fixes that).

**Comment by romainbsl** [comment]
Hey @dalewking, is your problem resolved?

**Comment by dalewking** [comment]
I just completed upgrading all dependencies and no longer have an issue
