### ISSUE TITLE
support wasm target

### ISSUE THREAD

**Issue by VladislavSumin** [kosi-libs/Kodein#433]
It is possibly to support wasm target? Coroutines and Compose libraries already have experimental wasm target support

**Comment by SalomonBrys** [comment]
Work in progress 😉

**Comment by romainbsl** [comment]
Wasm support as landed on Kodein [7.21.0](https://github.com/kosi-libs/Kodein/releases/tag/7.21.0).
Sorry about the delay, we had some issues we or build tools.
