### ISSUE TITLE
GraalVM Compatibility

### ISSUE THREAD

**Issue by NatsuOnFire** [kosi-libs/Kodein#434]
Hello,

I'd like to know if Kodein is compatible with GraalVM (native-image)?

If so, how can it be implemented and used?
If not, is this planned? Is there a date?

Thanks

**Comment by romainbsl** [comment]
Hi!

It is not, and not very planned to, as we don't have the use case. 
I am curious. What is yours?

**Comment by NatsuOnFire** [comment]
Hi

It's mainly for personal knowledge.
I made an application and to keep it light, I used ktor and kodein (instead of a framework like spring-boot).

And since my app wasn't working properly in native image mode, I thought it was because kodein was in lazy mode.
After several attempts, the problem wasn't kodein but another library.
