### ISSUE TITLE
Unable to generate Open Api documentation with OpenApi generator

### ISSUE THREAD

**Issue by sadiqueWiseboxs** [kosi-libs/Kodein#436]
Unable to generate the OpenApi documentation with the OpenApi generator plugin in JetBrains IntelliJ IDE when using controller

**Comment by romainbsl** [comment]
I don't understand what you are trying to achieve here 🤔 . 
Kodein has nothing to do with Open API generation. 
This is a Dependency Injection library not a backend development framework.
