### ISSUE TITLE
Testiminial images are broken in the README

### ISSUE THREAD

**Issue by SebastianAigner** [kosi-libs/Kodein#445]
Just figured I'd flag this since people might find these visual artifacts a bit odd :)

<img width="388" alt="Screenshot 2023-10-25 at 18 37 03" src="https://github.com/kosi-libs/Kodein/assets/2178959/e312fb9e-13f3-4917-a33c-a622396afa67">

**Comment by romainbsl** [comment]
Thanks for the report Sebastian.
I've just removed them. I will revamp the README page soon with a sructure.
