### ISSUE TITLE
Ktor 3 compatibility

### ISSUE THREAD

**Issue by stashymane** [kosi-libs/Kodein#454]
I have attempted to port Kodein to Ktor 3 myself, as only two changes were required, however one test is failing: https://github.com/stashymane/Kodein/commit/89a4d60fd72ecd24d4e0cd5c2caad05660559413

![image](https://github.com/kosi-libs/Kodein/assets/4071883/6dfb5657-e879-4076-bafc-96f623f33c21)

It seems that the call pipeline is being skipped for some reason. Otherwise the update is rather simple.
Here's the run for details: https://github.com/stashymane/Kodein/actions/runs/8818984587/job/24209096046

**Comment by Burtan** [comment]
I get errors with kodein 7.22.1 and ktor 3.0.0

```
Found interface io.ktor.server.routing.Routing, but class was expected
java.lang.IncompatibleClassChangeError: Found interface io.ktor.server.routing.Routing, but class was expected
	at org.kodein.di.ktor.ClosestKt.closestDI$lambda$2(closest.kt:32)
```

**Comment by Burtan** [comment]
I still get the same errors:

```
Found interface io.ktor.server.routing.Routing, but class was expected
java.lang.IncompatibleClassChangeError: Found interface io.ktor.server.routing.Routing, but class was expected
	at org.kodein.di.ktor.ClosestKt.closestDI$lambda$2(closest.kt:32)
```

Do you need anything?

**Comment by romainbsl** [comment]
Ktor 3 Compatibility has not been released in a stable release. 

You can try it on the snapshot channel.

**Comment by Burtan** [comment]
Ah, thanks, I somehow thought it was part of 7.23.1. Sorry!

**Comment by jvlka-jvlka** [comment]
@romainbsl, any news about stable version compatible with ktor 3.0.+ ?

**Comment by romainbsl** [comment]
It is available on SNAPSHOT, and it will probably come as is. I plan to work on Ktor plugin registry and compose related features before releasing a new version.

In the meantime, you can use it from the snapshot channel.
maven repository: https://s01.oss.sonatype.org/content/repositories/snapshots
target version of Kodein: 7.24.0-main-SNAPSHOT

**Comment by jvlka-jvlka** [comment]
Thanks for responding. In my company we are allow to use only stable versions. We ASAP need to upgrade ktor to 3.0.0. Did you have chance to work on new version?
