### ISSUE TITLE
KMP compatibility with version 7.22.0

### ISSUE THREAD

**Issue by oscarorozco-omron** [kosi-libs/Kodein#456]
I'm trying to add Kodein version 7.22.0 to a KMP project. I started the project with Android Studio KMP plugin template, with JVM 1.8 version and Gradle 8.5. However, when trying to build the project with gradle, I'm seeing a `Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option` error in the log. If I switch to version 7.21.2 everything works correctly.

The JDK version that it is used is 17.0.1.

<img width="241" alt="Screenshot 2024-07-17 at 1 00 51 PM" src="https://github.com/user-attachments/assets/581bb172-e592-4768-9b95-a68a1a8fc5b4">

<img width="588" alt="Screenshot 2024-07-17 at 1 03 44 PM" src="https://github.com/user-attachments/assets/649c0bc1-6796-4ecd-b645-c8d2274eb709">

**Comment by kodeplateform** [comment]
Same problem only on androidMain (MainActivcity)

**Comment by romainbsl** [comment]
We moved to JDK 11 minimum version, so in order to use Kodein 7.22+ you need to upgrade your project to JDK 11 as weel. 
JDK 1.8 is to old, Java 23 just came out...
